-- EXTENSIONS

CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";
CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgsodium";
CREATE EXTENSION IF NOT EXISTS "http" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "hypopg" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "index_advisor" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "postgres_fdw" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "public";
CREATE EXTENSION IF NOT EXISTS "wrappers" WITH SCHEMA "extensions";

-- TABLES

CREATE TABLE IF NOT EXISTS "public"."discussion_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" character varying(255),
    "discussion_id" bigint,
    "author" "text",
    "body" "text",
    "posted_at" timestamp without time zone,
    "embedding" "public"."vector"(384),
    "meta" "jsonb"
);

ALTER TABLE "public"."discussion_comments" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."discussions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" character varying(255),
    "discussion_number" integer,
    "title" "text",
    "author" "text",
    "body" "text",
    "opened_at" timestamp without time zone,
    "url" "text",
    "embedding" "public"."vector"(384),
    "meta" "jsonb"
);

ALTER TABLE "public"."discussions" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."issue_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" character varying(255),
    "issue_id" bigint,
    "author" "text",
    "body" "text",
    "posted_at" timestamp without time zone,
    "embedding" "public"."vector"(384),
    "meta" "jsonb"
);

ALTER TABLE "public"."issue_comments" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."issues" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" "text",
    "title" "text",
    "author" "text",
    "body" "text",
    "opened_at" timestamp without time zone,
    "closed_at" timestamp without time zone,
    "embedding" "public"."vector"(384),
    "url" "text",
    "state" "text",
    "meta" "jsonb",
    "updated_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE ONLY "public"."issues" REPLICA IDENTITY FULL;

ALTER TABLE "public"."issues" OWNER TO "postgres";

ALTER TABLE "public"."issues" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."issues_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" integer NOT NULL,
    "username" character varying(255) NOT NULL
);

ALTER TABLE "public"."users" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."users_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."users_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."users_id_seq" OWNED BY "public"."users"."id";

ALTER TABLE ONLY "public"."users" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."users_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."discussion_comments"
    ADD CONSTRAINT "discussion_comments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."discussions"
    ADD CONSTRAINT "discussions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."issue_comments"
    ADD CONSTRAINT "issue_comments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."issues"
    ADD CONSTRAINT "issues_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

CREATE INDEX "issue_comments_embedding_idx" ON "public"."issue_comments" USING "ivfflat" ("embedding" "public"."vector_cosine_ops") WITH ("lists"='468');

CREATE INDEX "issues_embedding_idx" ON "public"."issues" USING "ivfflat" ("embedding" "public"."vector_cosine_ops") WITH ("lists"='247');

ALTER TABLE ONLY "public"."discussion_comments"
    ADD CONSTRAINT "discussion_comments_discussion_id_fkey" FOREIGN KEY ("discussion_id") REFERENCES "public"."discussions"("id");



ALTER TABLE ONLY "public"."issue_comments"
    ADD CONSTRAINT "issue_comments_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "public"."issues"("id");


-- FUNCTIONS

CREATE OR REPLACE FUNCTION "public"."gen_embedding_trigger"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    embedding "public"."vector"(384);
BEGIN
RAISE NOTICE 'gen embed for new row : %', NEW.id;
SELECT content::jsonb->'embedding' into embedding
  FROM http((
          'POST',
           'https://qfsrmwxxufryrczocwuj.supabase.co/functions/v1/gen_embed',
           NULL,
           'application/json',
           jsonb_build_object('input', NEW.body)
        )::http_request);
    NEW.embedding := embedding;
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."gen_embedding_trigger"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."match_issues_with_embedding"("query_embedding" "public"."vector", "match_threshold" double precision, "match_count" integer) RETURNS TABLE("id" bigint, "title" "text", "description" "text", "similarity" double precision)
    LANGUAGE "plpgsql"
    AS $$
begin
  return query
    select
      issues.id,
      issues.title,
      issues.body as description,
      (embedding <#> query_embedding) as similarity
    from issues
    where (embedding <#> query_embedding) <= match_threshold
    order by similarity asc
    limit match_count;
end;
$$;


ALTER FUNCTION "public"."match_issues_with_embedding"("query_embedding" "public"."vector", "match_threshold" double precision, "match_count" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sync_github_issues"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    repo_url TEXT := 'https://api.github.com/repos/supabase/supabase/issues';
    response_data JSONB;
    response_headers http_header[];
    issue_record JSONB;
    existing_issue_id BIGINT;
    page_url TEXT;
    next_page_url TEXT;
    http_status INTEGER;
    rate_limit_remaining INTEGER;
    rate_limit_reset INTEGER;
    header_record http_header;
    link_header TEXT;
BEGIN
    page_url := repo_url || '?state=all&per_page=100&sort=updated&direction=desc';
    
    <<page_loop>>
    WHILE page_url IS NOT NULL LOOP
        BEGIN
            SELECT INTO response_data, http_status, response_headers
                content::jsonb, status, headers
            FROM http_get(page_url);
            
            IF http_status = 403 OR http_status = 429 THEN
                RAISE NOTICE 'Rate limit hit (status %). Stopping sync.', http_status;
                RAISE NOTICE 'Response: %', response_data;
                EXIT page_loop;
            END IF;
            
            IF http_status >= 400 THEN
                RAISE NOTICE 'HTTP error (status %). Stopping sync.', http_status;
                RAISE NOTICE 'Response: %', response_data;
                EXIT page_loop;
            END IF;
            
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Error making HTTP request: %', SQLERRM;
            EXIT page_loop;
        END;
        
        FOR issue_record IN SELECT * FROM jsonb_array_elements(response_data)
        LOOP
            -- Skip pull requests as they are also issues in GitHub API
            IF issue_record ? 'pull_request' THEN
                RAISE NOTICE 'Skipping pull request %', issue_record->>'id';
                CONTINUE;
            END IF;

            -- Check if issue already exists and has not changed
            SELECT id INTO existing_issue_id
            FROM issues
            WHERE id = (issue_record->>'id')::bigint 
              AND closed_at IS NOT DISTINCT FROM CASE
                    WHEN issue_record->>'closed_at' IS NOT NULL
                    THEN (issue_record->>'closed_at')::timestamp
                    ELSE NULL
                END
              AND body IS NOT DISTINCT FROM issue_record->>'body'
              AND state IS NOT DISTINCT FROM issue_record->>'state';

            IF existing_issue_id IS NOT NULL THEN
                RAISE NOTICE 'Skipping issue % as it already exists with same key fields', issue_record->>'id';
                CONTINUE;
            END IF;

            INSERT INTO issues (
                id,
                title,
                body,
                state,
                author,
                repository,
                url,
                opened_at,
                closed_at,
                meta
            ) VALUES (
                (issue_record->>'id')::bigint,
                issue_record->>'title',
                issue_record->>'body',
                issue_record->>'state',
                issue_record->'user'->>'login',
                'supabase/supabase',
                issue_record->>'html_url',
                (issue_record->>'created_at')::timestamp,
                CASE
                    WHEN issue_record->>'closed_at' IS NOT NULL
                    THEN (issue_record->>'closed_at')::timestamp
                    ELSE NULL
                END,
                issue_record
            )
            ON CONFLICT (id) DO UPDATE SET
                title = EXCLUDED.title,
                body = EXCLUDED.body,
                state = EXCLUDED.state,
                closed_at = EXCLUDED.closed_at,
                meta = EXCLUDED.meta,
                updated_at = now()
            WHERE issues.body IS DISTINCT FROM EXCLUDED.body
               OR issues.state IS DISTINCT FROM EXCLUDED.state
               OR issues.closed_at IS DISTINCT FROM EXCLUDED.closed_at;
        END LOOP;
        
        next_page_url := NULL;
        FOR i IN array_lower(response_headers, 1)..array_upper(response_headers, 1) LOOP
            header_record := response_headers[i];
            IF header_record.field = 'link' THEN
                link_header := header_record.value;
                IF link_header ~ '<([^>]+)>; rel="next"' THEN
                    next_page_url := substring(link_header from '<([^>]+)>; rel="next"');
                END IF;
                EXIT;
            END IF;
        END LOOP;
        page_url := next_page_url;
        IF page_url IS NULL THEN
            RAISE NOTICE 'No more pages to fetch';
        ELSE
            RAISE NOTICE 'Fetching next page: %', page_url;
        END IF;
    END LOOP page_loop;

    RAISE NOTICE 'Successfully synced GitHub issues';
END;
$$;

-- TRIGGERS

CREATE OR REPLACE TRIGGER "issue_embedding_trigger" AFTER INSERT OR UPDATE ON "public"."issues" FOR EACH ROW EXECUTE FUNCTION "public"."gen_embedding_trigger"();
