

CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";




CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE SCHEMA IF NOT EXISTS "stats";


ALTER SCHEMA "stats" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "citext" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "http" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "hypopg" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "index_advisor" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgaudit" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgmq";






CREATE EXTENSION IF NOT EXISTS "plpgsql_check" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "postgres_fdw" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "wrappers" WITH SCHEMA "extensions";


CREATE TABLE IF NOT EXISTS "public"."discussion_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" character varying(255),
    "discussion_id" bigint,
    "author" "text",
    "body" "text",
    "posted_at" timestamp without time zone,
    "embedding" "public"."vector"(384),
    "meta" "jsonb"
);


ALTER TABLE "public"."discussion_comments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."discussions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" character varying(255),
    "discussion_number" integer,
    "title" "text",
    "author" "text",
    "body" "text",
    "opened_at" timestamp without time zone,
    "url" "text",
    "embedding" "public"."vector"(384),
    "meta" "jsonb"
);


ALTER TABLE "public"."discussions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."issue_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" character varying(255),
    "issue_id" bigint,
    "author" "text",
    "body" "text",
    "posted_at" timestamp without time zone,
    "embedding" "public"."vector"(384),
    "meta" "jsonb"
);


ALTER TABLE "public"."issue_comments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."issues" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository" "text",
    "title" "text",
    "author" "text",
    "body" "text",
    "opened_at" timestamp without time zone,
    "closed_at" timestamp without time zone,
    "embedding" "public"."vector"(384),
    "url" "text",
    "state" "text",
    "meta" "jsonb",
    "updated_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE ONLY "public"."issues" REPLICA IDENTITY FULL;


ALTER TABLE "public"."issues" OWNER TO "postgres";


ALTER TABLE "public"."issues" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."issues_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.issue_comments
      ADD CONSTRAINT issue_comments_pkey PRIMARY KEY (id);




-- ALTER TABLE ONLY "public"."discussion_comments" ADD CONSTRAINT "discussion_comments_discussion_id_fkey" FOREIGN KEY ("discussion_id") REFERENCES "public"."discussions"("id");



-- ALTER TABLE ONLY "public"."issue_comments" ADD CONSTRAINT "issue_comments_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "public"."issues"("id");



CREATE POLICY "Enable read access for all users" ON "public"."issues" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."issue_comments" FOR SELECT USING (true);

ALTER TABLE "public"."issues" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."issue_comments" ENABLE ROW LEVEL SECURITY;


